#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ExpressTour")]
	public partial class ExpressTourDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Inserttransporte(transporte instance);
    partial void Updatetransporte(transporte instance);
    partial void Deletetransporte(transporte instance);
    partial void Insertempleado(empleado instance);
    partial void Updateempleado(empleado instance);
    partial void Deleteempleado(empleado instance);
    partial void Insertempleados_reserva(empleados_reserva instance);
    partial void Updateempleados_reserva(empleados_reserva instance);
    partial void Deleteempleados_reserva(empleados_reserva instance);
    partial void Insertexcursione(excursione instance);
    partial void Updateexcursione(excursione instance);
    partial void Deleteexcursione(excursione instance);
    partial void Insertfactura(factura instance);
    partial void Updatefactura(factura instance);
    partial void Deletefactura(factura instance);
    partial void Insertopiniones_cliente(opiniones_cliente instance);
    partial void Updateopiniones_cliente(opiniones_cliente instance);
    partial void Deleteopiniones_cliente(opiniones_cliente instance);
    partial void Insertpago(pago instance);
    partial void Updatepago(pago instance);
    partial void Deletepago(pago instance);
    partial void Insertpaquete(paquete instance);
    partial void Updatepaquete(paquete instance);
    partial void Deletepaquete(paquete instance);
    partial void Insertproveedore(proveedore instance);
    partial void Updateproveedore(proveedore instance);
    partial void Deleteproveedore(proveedore instance);
    partial void Insertreserva(reserva instance);
    partial void Updatereserva(reserva instance);
    partial void Deletereserva(reserva instance);
    partial void Insertreservas_excursione(reservas_excursione instance);
    partial void Updatereservas_excursione(reservas_excursione instance);
    partial void Deletereservas_excursione(reservas_excursione instance);
    #endregion
		
		public ExpressTourDataContext() : 
				base(global::DataLayer.Properties.Settings.Default.ExpressTourConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExpressTourDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpressTourDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpressTourDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpressTourDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<transporte> transportes
		{
			get
			{
				return this.GetTable<transporte>();
			}
		}
		
		public System.Data.Linq.Table<empleado> empleados
		{
			get
			{
				return this.GetTable<empleado>();
			}
		}
		
		public System.Data.Linq.Table<empleados_reserva> empleados_reservas
		{
			get
			{
				return this.GetTable<empleados_reserva>();
			}
		}
		
		public System.Data.Linq.Table<excursione> excursiones
		{
			get
			{
				return this.GetTable<excursione>();
			}
		}
		
		public System.Data.Linq.Table<factura> facturas
		{
			get
			{
				return this.GetTable<factura>();
			}
		}
		
		public System.Data.Linq.Table<opiniones_cliente> opiniones_clientes
		{
			get
			{
				return this.GetTable<opiniones_cliente>();
			}
		}
		
		public System.Data.Linq.Table<pago> pagos
		{
			get
			{
				return this.GetTable<pago>();
			}
		}
		
		public System.Data.Linq.Table<paquete> paquetes
		{
			get
			{
				return this.GetTable<paquete>();
			}
		}
		
		public System.Data.Linq.Table<proveedore> proveedores
		{
			get
			{
				return this.GetTable<proveedore>();
			}
		}
		
		public System.Data.Linq.Table<reserva> reservas
		{
			get
			{
				return this.GetTable<reserva>();
			}
		}
		
		public System.Data.Linq.Table<reservas_excursione> reservas_excursiones
		{
			get
			{
				return this.GetTable<reservas_excursione>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cliente;
		
		private string _nombre;
		
		private string _correo;
		
		private string _telefono;
		
		private string _direccion;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private EntitySet<opiniones_cliente> _opiniones_clientes;
		
		private EntitySet<reserva> _reservas;
		
		private EntitySet<reservas_excursione> _reservas_excursiones;
        public object Apellido;
        public object Email;

        #region Extensibility Method Definitions
        partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Onfecha_registroChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_registroChanged();
    #endregion
		
		public cliente()
		{
			this._opiniones_clientes = new EntitySet<opiniones_cliente>(new Action<opiniones_cliente>(this.attach_opiniones_clientes), new Action<opiniones_cliente>(this.detach_opiniones_clientes));
			this._reservas = new EntitySet<reserva>(new Action<reserva>(this.attach_reservas), new Action<reserva>(this.detach_reservas));
			this._reservas_excursiones = new EntitySet<reservas_excursione>(new Action<reservas_excursione>(this.attach_reservas_excursiones), new Action<reservas_excursione>(this.detach_reservas_excursiones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(15)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_opiniones_cliente", Storage="_opiniones_clientes", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<opiniones_cliente> opiniones_clientes
		{
			get
			{
				return this._opiniones_clientes;
			}
			set
			{
				this._opiniones_clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_reserva", Storage="_reservas", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<reserva> reservas
		{
			get
			{
				return this._reservas;
			}
			set
			{
				this._reservas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_reservas_excursione", Storage="_reservas_excursiones", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<reservas_excursione> reservas_excursiones
		{
			get
			{
				return this._reservas_excursiones;
			}
			set
			{
				this._reservas_excursiones.Assign(value);
			}
		}

        public int Id { get; set; }
        public int id { get; set; }

        public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_opiniones_clientes(opiniones_cliente entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_opiniones_clientes(opiniones_cliente entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
		
		private void attach_reservas(reserva entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_reservas(reserva entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
		
		private void attach_reservas_excursiones(reservas_excursione entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_reservas_excursiones(reservas_excursione entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.transporte")]
	public partial class transporte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_transporte;
		
		private string _tipo;
		
		private int _capacidad;
		
		private string _placa;
		
		private string _estado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_transporteChanging(int value);
    partial void Onid_transporteChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OncapacidadChanging(int value);
    partial void OncapacidadChanged();
    partial void OnplacaChanging(string value);
    partial void OnplacaChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public transporte()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_transporte", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_transporte
		{
			get
			{
				return this._id_transporte;
			}
			set
			{
				if ((this._id_transporte != value))
				{
					this.Onid_transporteChanging(value);
					this.SendPropertyChanging();
					this._id_transporte = value;
					this.SendPropertyChanged("id_transporte");
					this.Onid_transporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacidad", DbType="Int NOT NULL")]
		public int capacidad
		{
			get
			{
				return this._capacidad;
			}
			set
			{
				if ((this._capacidad != value))
				{
					this.OncapacidadChanging(value);
					this.SendPropertyChanging();
					this._capacidad = value;
					this.SendPropertyChanged("capacidad");
					this.OncapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placa", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string placa
		{
			get
			{
				return this._placa;
			}
			set
			{
				if ((this._placa != value))
				{
					this.OnplacaChanging(value);
					this.SendPropertyChanging();
					this._placa = value;
					this.SendPropertyChanged("placa");
					this.OnplacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(20)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.empleados")]
	public partial class empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_empleado;
		
		private string _nombre;
		
		private string _puesto;
		
		private System.Nullable<decimal> _salario;
		
		private System.Nullable<System.DateTime> _fecha_contratacion;
		
		private string _correo;
		
		private EntitySet<empleados_reserva> _empleados_reservas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_empleadoChanging(int value);
    partial void Onid_empleadoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnpuestoChanging(string value);
    partial void OnpuestoChanged();
    partial void OnsalarioChanging(System.Nullable<decimal> value);
    partial void OnsalarioChanged();
    partial void Onfecha_contratacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_contratacionChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    #endregion
		
		public empleado()
		{
			this._empleados_reservas = new EntitySet<empleados_reserva>(new Action<empleados_reserva>(this.attach_empleados_reservas), new Action<empleados_reserva>(this.detach_empleados_reservas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_empleado
		{
			get
			{
				return this._id_empleado;
			}
			set
			{
				if ((this._id_empleado != value))
				{
					this.Onid_empleadoChanging(value);
					this.SendPropertyChanging();
					this._id_empleado = value;
					this.SendPropertyChanged("id_empleado");
					this.Onid_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puesto", DbType="NVarChar(50)")]
		public string puesto
		{
			get
			{
				return this._puesto;
			}
			set
			{
				if ((this._puesto != value))
				{
					this.OnpuestoChanging(value);
					this.SendPropertyChanging();
					this._puesto = value;
					this.SendPropertyChanged("puesto");
					this.OnpuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salario", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> salario
		{
			get
			{
				return this._salario;
			}
			set
			{
				if ((this._salario != value))
				{
					this.OnsalarioChanging(value);
					this.SendPropertyChanging();
					this._salario = value;
					this.SendPropertyChanged("salario");
					this.OnsalarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_contratacion", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_contratacion
		{
			get
			{
				return this._fecha_contratacion;
			}
			set
			{
				if ((this._fecha_contratacion != value))
				{
					this.Onfecha_contratacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_contratacion = value;
					this.SendPropertyChanged("fecha_contratacion");
					this.Onfecha_contratacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="empleado_empleados_reserva", Storage="_empleados_reservas", ThisKey="id_empleado", OtherKey="id_empleado")]
		public EntitySet<empleados_reserva> empleados_reservas
		{
			get
			{
				return this._empleados_reservas;
			}
			set
			{
				this._empleados_reservas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_empleados_reservas(empleados_reserva entity)
		{
			this.SendPropertyChanging();
			entity.empleado = this;
		}
		
		private void detach_empleados_reservas(empleados_reserva entity)
		{
			this.SendPropertyChanging();
			entity.empleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.empleados_reservas")]
	public partial class empleados_reserva : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_empleado_reserva;
		
		private int _id_empleado;
		
		private int _id_reserva;
		
		private string _rol;
		
		private EntityRef<empleado> _empleado;
		
		private EntityRef<reserva> _reserva;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_empleado_reservaChanging(int value);
    partial void Onid_empleado_reservaChanged();
    partial void Onid_empleadoChanging(int value);
    partial void Onid_empleadoChanged();
    partial void Onid_reservaChanging(int value);
    partial void Onid_reservaChanged();
    partial void OnrolChanging(string value);
    partial void OnrolChanged();
    #endregion
		
		public empleados_reserva()
		{
			this._empleado = default(EntityRef<empleado>);
			this._reserva = default(EntityRef<reserva>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado_reserva", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_empleado_reserva
		{
			get
			{
				return this._id_empleado_reserva;
			}
			set
			{
				if ((this._id_empleado_reserva != value))
				{
					this.Onid_empleado_reservaChanging(value);
					this.SendPropertyChanging();
					this._id_empleado_reserva = value;
					this.SendPropertyChanged("id_empleado_reserva");
					this.Onid_empleado_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado", DbType="Int NOT NULL")]
		public int id_empleado
		{
			get
			{
				return this._id_empleado;
			}
			set
			{
				if ((this._id_empleado != value))
				{
					if (this._empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_empleadoChanging(value);
					this.SendPropertyChanging();
					this._id_empleado = value;
					this.SendPropertyChanged("id_empleado");
					this.Onid_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reserva", DbType="Int NOT NULL")]
		public int id_reserva
		{
			get
			{
				return this._id_reserva;
			}
			set
			{
				if ((this._id_reserva != value))
				{
					if (this._reserva.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_reservaChanging(value);
					this.SendPropertyChanging();
					this._id_reserva = value;
					this.SendPropertyChanged("id_reserva");
					this.Onid_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this.OnrolChanging(value);
					this.SendPropertyChanging();
					this._rol = value;
					this.SendPropertyChanged("rol");
					this.OnrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="empleado_empleados_reserva", Storage="_empleado", ThisKey="id_empleado", OtherKey="id_empleado", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public empleado empleado
		{
			get
			{
				return this._empleado.Entity;
			}
			set
			{
				empleado previousValue = this._empleado.Entity;
				if (((previousValue != value) 
							|| (this._empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._empleado.Entity = null;
						previousValue.empleados_reservas.Remove(this);
					}
					this._empleado.Entity = value;
					if ((value != null))
					{
						value.empleados_reservas.Add(this);
						this._id_empleado = value.id_empleado;
					}
					else
					{
						this._id_empleado = default(int);
					}
					this.SendPropertyChanged("empleado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reserva_empleados_reserva", Storage="_reserva", ThisKey="id_reserva", OtherKey="id_reserva", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public reserva reserva
		{
			get
			{
				return this._reserva.Entity;
			}
			set
			{
				reserva previousValue = this._reserva.Entity;
				if (((previousValue != value) 
							|| (this._reserva.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._reserva.Entity = null;
						previousValue.empleados_reservas.Remove(this);
					}
					this._reserva.Entity = value;
					if ((value != null))
					{
						value.empleados_reservas.Add(this);
						this._id_reserva = value.id_reserva;
					}
					else
					{
						this._id_reserva = default(int);
					}
					this.SendPropertyChanged("reserva");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.excursiones")]
	public partial class excursione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_excursion;
		
		private string _nombre;
		
		private string _descripcion;
		
		private decimal _precio;
		
		private int _capacidad;
		
		private EntitySet<reservas_excursione> _reservas_excursiones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_excursionChanging(int value);
    partial void Onid_excursionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    partial void OncapacidadChanging(int value);
    partial void OncapacidadChanged();
    #endregion
		
		public excursione()
		{
			this._reservas_excursiones = new EntitySet<reservas_excursione>(new Action<reservas_excursione>(this.attach_reservas_excursiones), new Action<reservas_excursione>(this.detach_reservas_excursiones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_excursion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_excursion
		{
			get
			{
				return this._id_excursion;
			}
			set
			{
				if ((this._id_excursion != value))
				{
					this.Onid_excursionChanging(value);
					this.SendPropertyChanging();
					this._id_excursion = value;
					this.SendPropertyChanged("id_excursion");
					this.Onid_excursionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2) NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacidad", DbType="Int NOT NULL")]
		public int capacidad
		{
			get
			{
				return this._capacidad;
			}
			set
			{
				if ((this._capacidad != value))
				{
					this.OncapacidadChanging(value);
					this.SendPropertyChanging();
					this._capacidad = value;
					this.SendPropertyChanged("capacidad");
					this.OncapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="excursione_reservas_excursione", Storage="_reservas_excursiones", ThisKey="id_excursion", OtherKey="id_excursion")]
		public EntitySet<reservas_excursione> reservas_excursiones
		{
			get
			{
				return this._reservas_excursiones;
			}
			set
			{
				this._reservas_excursiones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_reservas_excursiones(reservas_excursione entity)
		{
			this.SendPropertyChanging();
			entity.excursione = this;
		}
		
		private void detach_reservas_excursiones(reservas_excursione entity)
		{
			this.SendPropertyChanging();
			entity.excursione = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.facturas")]
	public partial class factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_factura;
		
		private int _id_reserva;
		
		private decimal _total;
		
		private System.Nullable<System.DateTime> _fecha_emision;
		
		private string _metodo_pago;
		
		private EntityRef<reserva> _reserva;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_facturaChanging(int value);
    partial void Onid_facturaChanged();
    partial void Onid_reservaChanging(int value);
    partial void Onid_reservaChanged();
    partial void OntotalChanging(decimal value);
    partial void OntotalChanged();
    partial void Onfecha_emisionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_emisionChanged();
    partial void Onmetodo_pagoChanging(string value);
    partial void Onmetodo_pagoChanged();
    #endregion
		
		public factura()
		{
			this._reserva = default(EntityRef<reserva>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_factura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_factura
		{
			get
			{
				return this._id_factura;
			}
			set
			{
				if ((this._id_factura != value))
				{
					this.Onid_facturaChanging(value);
					this.SendPropertyChanging();
					this._id_factura = value;
					this.SendPropertyChanged("id_factura");
					this.Onid_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reserva", DbType="Int NOT NULL")]
		public int id_reserva
		{
			get
			{
				return this._id_reserva;
			}
			set
			{
				if ((this._id_reserva != value))
				{
					if (this._reserva.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_reservaChanging(value);
					this.SendPropertyChanging();
					this._id_reserva = value;
					this.SendPropertyChanged("id_reserva");
					this.Onid_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(10,2) NOT NULL")]
		public decimal total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_emision", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_emision
		{
			get
			{
				return this._fecha_emision;
			}
			set
			{
				if ((this._fecha_emision != value))
				{
					this.Onfecha_emisionChanging(value);
					this.SendPropertyChanging();
					this._fecha_emision = value;
					this.SendPropertyChanged("fecha_emision");
					this.Onfecha_emisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metodo_pago", DbType="NVarChar(50)")]
		public string metodo_pago
		{
			get
			{
				return this._metodo_pago;
			}
			set
			{
				if ((this._metodo_pago != value))
				{
					this.Onmetodo_pagoChanging(value);
					this.SendPropertyChanging();
					this._metodo_pago = value;
					this.SendPropertyChanged("metodo_pago");
					this.Onmetodo_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reserva_factura", Storage="_reserva", ThisKey="id_reserva", OtherKey="id_reserva", IsForeignKey=true)]
		public reserva reserva
		{
			get
			{
				return this._reserva.Entity;
			}
			set
			{
				reserva previousValue = this._reserva.Entity;
				if (((previousValue != value) 
							|| (this._reserva.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._reserva.Entity = null;
						previousValue.facturas.Remove(this);
					}
					this._reserva.Entity = value;
					if ((value != null))
					{
						value.facturas.Add(this);
						this._id_reserva = value.id_reserva;
					}
					else
					{
						this._id_reserva = default(int);
					}
					this.SendPropertyChanged("reserva");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.opiniones_clientes")]
	public partial class opiniones_cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_opinion;
		
		private int _id_cliente;
		
		private int _id_paquete;
		
		private System.Nullable<int> _calificacion;
		
		private string _comentario;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _respuesta_empresa;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<paquete> _paquete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_opinionChanging(int value);
    partial void Onid_opinionChanged();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Onid_paqueteChanging(int value);
    partial void Onid_paqueteChanged();
    partial void OncalificacionChanging(System.Nullable<int> value);
    partial void OncalificacionChanged();
    partial void OncomentarioChanging(string value);
    partial void OncomentarioChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void Onrespuesta_empresaChanging(string value);
    partial void Onrespuesta_empresaChanged();
    #endregion
		
		public opiniones_cliente()
		{
			this._cliente = default(EntityRef<cliente>);
			this._paquete = default(EntityRef<paquete>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_opinion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_opinion
		{
			get
			{
				return this._id_opinion;
			}
			set
			{
				if ((this._id_opinion != value))
				{
					this.Onid_opinionChanging(value);
					this.SendPropertyChanging();
					this._id_opinion = value;
					this.SendPropertyChanged("id_opinion");
					this.Onid_opinionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int NOT NULL")]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paquete", DbType="Int NOT NULL")]
		public int id_paquete
		{
			get
			{
				return this._id_paquete;
			}
			set
			{
				if ((this._id_paquete != value))
				{
					if (this._paquete.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_paqueteChanging(value);
					this.SendPropertyChanging();
					this._id_paquete = value;
					this.SendPropertyChanged("id_paquete");
					this.Onid_paqueteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion", DbType="Int")]
		public System.Nullable<int> calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				if ((this._calificacion != value))
				{
					this.OncalificacionChanging(value);
					this.SendPropertyChanging();
					this._calificacion = value;
					this.SendPropertyChanged("calificacion");
					this.OncalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario", DbType="NVarChar(MAX)")]
		public string comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				if ((this._comentario != value))
				{
					this.OncomentarioChanging(value);
					this.SendPropertyChanging();
					this._comentario = value;
					this.SendPropertyChanged("comentario");
					this.OncomentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_respuesta_empresa", DbType="NVarChar(MAX)")]
		public string respuesta_empresa
		{
			get
			{
				return this._respuesta_empresa;
			}
			set
			{
				if ((this._respuesta_empresa != value))
				{
					this.Onrespuesta_empresaChanging(value);
					this.SendPropertyChanging();
					this._respuesta_empresa = value;
					this.SendPropertyChanged("respuesta_empresa");
					this.Onrespuesta_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_opiniones_cliente", Storage="_cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.opiniones_clientes.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.opiniones_clientes.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(int);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paquete_opiniones_cliente", Storage="_paquete", ThisKey="id_paquete", OtherKey="id_paquete", IsForeignKey=true)]
		public paquete paquete
		{
			get
			{
				return this._paquete.Entity;
			}
			set
			{
				paquete previousValue = this._paquete.Entity;
				if (((previousValue != value) 
							|| (this._paquete.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._paquete.Entity = null;
						previousValue.opiniones_clientes.Remove(this);
					}
					this._paquete.Entity = value;
					if ((value != null))
					{
						value.opiniones_clientes.Add(this);
						this._id_paquete = value.id_paquete;
					}
					else
					{
						this._id_paquete = default(int);
					}
					this.SendPropertyChanged("paquete");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pagos")]
	public partial class pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pago;
		
		private int _id_reserva;
		
		private decimal _monto;
		
		private string _metodo_pago;
		
		private System.Nullable<System.DateTime> _fecha_pago;
		
		private string _referencia_pago;
		
		private EntityRef<reserva> _reserva;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pagoChanging(int value);
    partial void Onid_pagoChanged();
    partial void Onid_reservaChanging(int value);
    partial void Onid_reservaChanged();
    partial void OnmontoChanging(decimal value);
    partial void OnmontoChanged();
    partial void Onmetodo_pagoChanging(string value);
    partial void Onmetodo_pagoChanged();
    partial void Onfecha_pagoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_pagoChanged();
    partial void Onreferencia_pagoChanging(string value);
    partial void Onreferencia_pagoChanged();
    #endregion
		
		public pago()
		{
			this._reserva = default(EntityRef<reserva>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pago
		{
			get
			{
				return this._id_pago;
			}
			set
			{
				if ((this._id_pago != value))
				{
					this.Onid_pagoChanging(value);
					this.SendPropertyChanging();
					this._id_pago = value;
					this.SendPropertyChanged("id_pago");
					this.Onid_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reserva", DbType="Int NOT NULL")]
		public int id_reserva
		{
			get
			{
				return this._id_reserva;
			}
			set
			{
				if ((this._id_reserva != value))
				{
					if (this._reserva.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_reservaChanging(value);
					this.SendPropertyChanging();
					this._id_reserva = value;
					this.SendPropertyChanged("id_reserva");
					this.Onid_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto", DbType="Decimal(10,2) NOT NULL")]
		public decimal monto
		{
			get
			{
				return this._monto;
			}
			set
			{
				if ((this._monto != value))
				{
					this.OnmontoChanging(value);
					this.SendPropertyChanging();
					this._monto = value;
					this.SendPropertyChanged("monto");
					this.OnmontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metodo_pago", DbType="NVarChar(50)")]
		public string metodo_pago
		{
			get
			{
				return this._metodo_pago;
			}
			set
			{
				if ((this._metodo_pago != value))
				{
					this.Onmetodo_pagoChanging(value);
					this.SendPropertyChanging();
					this._metodo_pago = value;
					this.SendPropertyChanged("metodo_pago");
					this.Onmetodo_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_pago", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_pago
		{
			get
			{
				return this._fecha_pago;
			}
			set
			{
				if ((this._fecha_pago != value))
				{
					this.Onfecha_pagoChanging(value);
					this.SendPropertyChanging();
					this._fecha_pago = value;
					this.SendPropertyChanged("fecha_pago");
					this.Onfecha_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia_pago", DbType="NVarChar(100)")]
		public string referencia_pago
		{
			get
			{
				return this._referencia_pago;
			}
			set
			{
				if ((this._referencia_pago != value))
				{
					this.Onreferencia_pagoChanging(value);
					this.SendPropertyChanging();
					this._referencia_pago = value;
					this.SendPropertyChanged("referencia_pago");
					this.Onreferencia_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reserva_pago", Storage="_reserva", ThisKey="id_reserva", OtherKey="id_reserva", IsForeignKey=true)]
		public reserva reserva
		{
			get
			{
				return this._reserva.Entity;
			}
			set
			{
				reserva previousValue = this._reserva.Entity;
				if (((previousValue != value) 
							|| (this._reserva.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._reserva.Entity = null;
						previousValue.pagos.Remove(this);
					}
					this._reserva.Entity = value;
					if ((value != null))
					{
						value.pagos.Add(this);
						this._id_reserva = value.id_reserva;
					}
					else
					{
						this._id_reserva = default(int);
					}
					this.SendPropertyChanged("reserva");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.paquetes")]
	public partial class paquete : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_paquete;
		
		private string _nombre;
		
		private string _descripcion;
		
		private decimal _precio;
		
		private int _duracion_dias;
		
		private string _categoria;
		
		private EntitySet<opiniones_cliente> _opiniones_clientes;
		
		private EntitySet<reserva> _reservas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_paqueteChanging(int value);
    partial void Onid_paqueteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    partial void Onduracion_diasChanging(int value);
    partial void Onduracion_diasChanged();
    partial void OncategoriaChanging(string value);
    partial void OncategoriaChanged();
    #endregion
		
		public paquete()
		{
			this._opiniones_clientes = new EntitySet<opiniones_cliente>(new Action<opiniones_cliente>(this.attach_opiniones_clientes), new Action<opiniones_cliente>(this.detach_opiniones_clientes));
			this._reservas = new EntitySet<reserva>(new Action<reserva>(this.attach_reservas), new Action<reserva>(this.detach_reservas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paquete", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_paquete
		{
			get
			{
				return this._id_paquete;
			}
			set
			{
				if ((this._id_paquete != value))
				{
					this.Onid_paqueteChanging(value);
					this.SendPropertyChanging();
					this._id_paquete = value;
					this.SendPropertyChanged("id_paquete");
					this.Onid_paqueteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2) NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracion_dias", DbType="Int NOT NULL")]
		public int duracion_dias
		{
			get
			{
				return this._duracion_dias;
			}
			set
			{
				if ((this._duracion_dias != value))
				{
					this.Onduracion_diasChanging(value);
					this.SendPropertyChanging();
					this._duracion_dias = value;
					this.SendPropertyChanged("duracion_dias");
					this.Onduracion_diasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="NVarChar(50)")]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this.OncategoriaChanging(value);
					this.SendPropertyChanging();
					this._categoria = value;
					this.SendPropertyChanged("categoria");
					this.OncategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paquete_opiniones_cliente", Storage="_opiniones_clientes", ThisKey="id_paquete", OtherKey="id_paquete")]
		public EntitySet<opiniones_cliente> opiniones_clientes
		{
			get
			{
				return this._opiniones_clientes;
			}
			set
			{
				this._opiniones_clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paquete_reserva", Storage="_reservas", ThisKey="id_paquete", OtherKey="id_paquete")]
		public EntitySet<reserva> reservas
		{
			get
			{
				return this._reservas;
			}
			set
			{
				this._reservas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_opiniones_clientes(opiniones_cliente entity)
		{
			this.SendPropertyChanging();
			entity.paquete = this;
		}
		
		private void detach_opiniones_clientes(opiniones_cliente entity)
		{
			this.SendPropertyChanging();
			entity.paquete = null;
		}
		
		private void attach_reservas(reserva entity)
		{
			this.SendPropertyChanging();
			entity.paquete = this;
		}
		
		private void detach_reservas(reserva entity)
		{
			this.SendPropertyChanging();
			entity.paquete = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.proveedores")]
	public partial class proveedore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_proveedor;
		
		private string _nombre;
		
		private string _contacto;
		
		private string _telefono;
		
		private string _correo;
		
		private string _direccion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_proveedorChanging(int value);
    partial void Onid_proveedorChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncontactoChanging(string value);
    partial void OncontactoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    #endregion
		
		public proveedore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proveedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_proveedor
		{
			get
			{
				return this._id_proveedor;
			}
			set
			{
				if ((this._id_proveedor != value))
				{
					this.Onid_proveedorChanging(value);
					this.SendPropertyChanging();
					this._id_proveedor = value;
					this.SendPropertyChanged("id_proveedor");
					this.Onid_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contacto", DbType="NVarChar(100)")]
		public string contacto
		{
			get
			{
				return this._contacto;
			}
			set
			{
				if ((this._contacto != value))
				{
					this.OncontactoChanging(value);
					this.SendPropertyChanging();
					this._contacto = value;
					this.SendPropertyChanged("contacto");
					this.OncontactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(15)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reservas")]
	public partial class reserva : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_reserva;
		
		private int _id_cliente;
		
		private int _id_paquete;
		
		private System.Nullable<System.DateTime> _fecha_reserva;
		
		private string _estado;
		
		private string _comentarios;
		
		private EntitySet<empleados_reserva> _empleados_reservas;
		
		private EntitySet<factura> _facturas;
		
		private EntitySet<pago> _pagos;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<paquete> _paquete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_reservaChanging(int value);
    partial void Onid_reservaChanged();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Onid_paqueteChanging(int value);
    partial void Onid_paqueteChanged();
    partial void Onfecha_reservaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_reservaChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OncomentariosChanging(string value);
    partial void OncomentariosChanged();
    #endregion
		
		public reserva()
		{
			this._empleados_reservas = new EntitySet<empleados_reserva>(new Action<empleados_reserva>(this.attach_empleados_reservas), new Action<empleados_reserva>(this.detach_empleados_reservas));
			this._facturas = new EntitySet<factura>(new Action<factura>(this.attach_facturas), new Action<factura>(this.detach_facturas));
			this._pagos = new EntitySet<pago>(new Action<pago>(this.attach_pagos), new Action<pago>(this.detach_pagos));
			this._cliente = default(EntityRef<cliente>);
			this._paquete = default(EntityRef<paquete>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reserva", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_reserva
		{
			get
			{
				return this._id_reserva;
			}
			set
			{
				if ((this._id_reserva != value))
				{
					this.Onid_reservaChanging(value);
					this.SendPropertyChanging();
					this._id_reserva = value;
					this.SendPropertyChanged("id_reserva");
					this.Onid_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int NOT NULL")]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paquete", DbType="Int NOT NULL")]
		public int id_paquete
		{
			get
			{
				return this._id_paquete;
			}
			set
			{
				if ((this._id_paquete != value))
				{
					if (this._paquete.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_paqueteChanging(value);
					this.SendPropertyChanging();
					this._id_paquete = value;
					this.SendPropertyChanged("id_paquete");
					this.Onid_paqueteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reserva", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_reserva
		{
			get
			{
				return this._fecha_reserva;
			}
			set
			{
				if ((this._fecha_reserva != value))
				{
					this.Onfecha_reservaChanging(value);
					this.SendPropertyChanging();
					this._fecha_reserva = value;
					this.SendPropertyChanged("fecha_reserva");
					this.Onfecha_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(20)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentarios", DbType="NVarChar(MAX)")]
		public string comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				if ((this._comentarios != value))
				{
					this.OncomentariosChanging(value);
					this.SendPropertyChanging();
					this._comentarios = value;
					this.SendPropertyChanged("comentarios");
					this.OncomentariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reserva_empleados_reserva", Storage="_empleados_reservas", ThisKey="id_reserva", OtherKey="id_reserva")]
		public EntitySet<empleados_reserva> empleados_reservas
		{
			get
			{
				return this._empleados_reservas;
			}
			set
			{
				this._empleados_reservas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reserva_factura", Storage="_facturas", ThisKey="id_reserva", OtherKey="id_reserva")]
		public EntitySet<factura> facturas
		{
			get
			{
				return this._facturas;
			}
			set
			{
				this._facturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reserva_pago", Storage="_pagos", ThisKey="id_reserva", OtherKey="id_reserva")]
		public EntitySet<pago> pagos
		{
			get
			{
				return this._pagos;
			}
			set
			{
				this._pagos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_reserva", Storage="_cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.reservas.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.reservas.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(int);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paquete_reserva", Storage="_paquete", ThisKey="id_paquete", OtherKey="id_paquete", IsForeignKey=true)]
		public paquete paquete
		{
			get
			{
				return this._paquete.Entity;
			}
			set
			{
				paquete previousValue = this._paquete.Entity;
				if (((previousValue != value) 
							|| (this._paquete.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._paquete.Entity = null;
						previousValue.reservas.Remove(this);
					}
					this._paquete.Entity = value;
					if ((value != null))
					{
						value.reservas.Add(this);
						this._id_paquete = value.id_paquete;
					}
					else
					{
						this._id_paquete = default(int);
					}
					this.SendPropertyChanged("paquete");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_empleados_reservas(empleados_reserva entity)
		{
			this.SendPropertyChanging();
			entity.reserva = this;
		}
		
		private void detach_empleados_reservas(empleados_reserva entity)
		{
			this.SendPropertyChanging();
			entity.reserva = null;
		}
		
		private void attach_facturas(factura entity)
		{
			this.SendPropertyChanging();
			entity.reserva = this;
		}
		
		private void detach_facturas(factura entity)
		{
			this.SendPropertyChanging();
			entity.reserva = null;
		}
		
		private void attach_pagos(pago entity)
		{
			this.SendPropertyChanging();
			entity.reserva = this;
		}
		
		private void detach_pagos(pago entity)
		{
			this.SendPropertyChanging();
			entity.reserva = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reservas_excursiones")]
	public partial class reservas_excursione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_reserva_excursion;
		
		private int _id_cliente;
		
		private int _id_excursion;
		
		private System.Nullable<System.DateTime> _fecha_reserva;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<excursione> _excursione;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_reserva_excursionChanging(int value);
    partial void Onid_reserva_excursionChanged();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Onid_excursionChanging(int value);
    partial void Onid_excursionChanged();
    partial void Onfecha_reservaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_reservaChanged();
    #endregion
		
		public reservas_excursione()
		{
			this._cliente = default(EntityRef<cliente>);
			this._excursione = default(EntityRef<excursione>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reserva_excursion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_reserva_excursion
		{
			get
			{
				return this._id_reserva_excursion;
			}
			set
			{
				if ((this._id_reserva_excursion != value))
				{
					this.Onid_reserva_excursionChanging(value);
					this.SendPropertyChanging();
					this._id_reserva_excursion = value;
					this.SendPropertyChanged("id_reserva_excursion");
					this.Onid_reserva_excursionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int NOT NULL")]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_excursion", DbType="Int NOT NULL")]
		public int id_excursion
		{
			get
			{
				return this._id_excursion;
			}
			set
			{
				if ((this._id_excursion != value))
				{
					if (this._excursione.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_excursionChanging(value);
					this.SendPropertyChanging();
					this._id_excursion = value;
					this.SendPropertyChanged("id_excursion");
					this.Onid_excursionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reserva", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_reserva
		{
			get
			{
				return this._fecha_reserva;
			}
			set
			{
				if ((this._fecha_reserva != value))
				{
					this.Onfecha_reservaChanging(value);
					this.SendPropertyChanging();
					this._fecha_reserva = value;
					this.SendPropertyChanged("fecha_reserva");
					this.Onfecha_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_reservas_excursione", Storage="_cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.reservas_excursiones.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.reservas_excursiones.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(int);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="excursione_reservas_excursione", Storage="_excursione", ThisKey="id_excursion", OtherKey="id_excursion", IsForeignKey=true)]
		public excursione excursione
		{
			get
			{
				return this._excursione.Entity;
			}
			set
			{
				excursione previousValue = this._excursione.Entity;
				if (((previousValue != value) 
							|| (this._excursione.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._excursione.Entity = null;
						previousValue.reservas_excursiones.Remove(this);
					}
					this._excursione.Entity = value;
					if ((value != null))
					{
						value.reservas_excursiones.Add(this);
						this._id_excursion = value.id_excursion;
					}
					else
					{
						this._id_excursion = default(int);
					}
					this.SendPropertyChanged("excursione");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
