#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ExpressTour")]
	public partial class ExpressTourDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Inserttransporte(transporte instance);
    partial void Updatetransporte(transporte instance);
    partial void Deletetransporte(transporte instance);
    partial void Insertexcursiones(excursiones instance);
    partial void Updateexcursiones(excursiones instance);
    partial void Deleteexcursiones(excursiones instance);
    partial void Insertfactura(factura instance);
    partial void Updatefactura(factura instance);
    partial void Deletefactura(factura instance);
    partial void Insertopiniones_cliente(opiniones_cliente instance);
    partial void Updateopiniones_cliente(opiniones_cliente instance);
    partial void Deleteopiniones_cliente(opiniones_cliente instance);
    partial void Insertpaquete(paquete instance);
    partial void Updatepaquete(paquete instance);
    partial void Deletepaquete(paquete instance);
    partial void Insertproveedore(proveedore instance);
    partial void Updateproveedore(proveedore instance);
    partial void Deleteproveedore(proveedore instance);
    partial void Insertreserva(reserva instance);
    partial void Updatereserva(reserva instance);
    partial void Deletereserva(reserva instance);
    partial void Insertpaquetes_excursione(paquetes_excursione instance);
    partial void Updatepaquetes_excursione(paquetes_excursione instance);
    partial void Deletepaquetes_excursione(paquetes_excursione instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public ExpressTourDataContext() : 
				base(global::DataLayer.Properties.Settings.Default.ExpressTourConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExpressTourDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpressTourDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpressTourDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpressTourDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<transporte> transportes
		{
			get
			{
				return this.GetTable<transporte>();
			}
		}
		
		public System.Data.Linq.Table<excursiones> excursiones
		{
			get
			{
				return this.GetTable<excursiones>();
			}
		}
		
		public System.Data.Linq.Table<factura> facturas
		{
			get
			{
				return this.GetTable<factura>();
			}
		}
		
		public System.Data.Linq.Table<opiniones_cliente> opiniones_clientes
		{
			get
			{
				return this.GetTable<opiniones_cliente>();
			}
		}
		
		public System.Data.Linq.Table<paquete> paquetes
		{
			get
			{
				return this.GetTable<paquete>();
			}
		}
		
		public System.Data.Linq.Table<proveedore> proveedores
		{
			get
			{
				return this.GetTable<proveedore>();
			}
		}
		
		public System.Data.Linq.Table<reserva> reservas
		{
			get
			{
				return this.GetTable<reserva>();
			}
		}
		
		public System.Data.Linq.Table<paquetes_excursione> paquetes_excursiones
		{
			get
			{
				return this.GetTable<paquetes_excursione>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cliente;
		
		private string _nombre;
		
		private string _correo;
		
		private string _telefono;
		
		private string _direccion;
		
		private EntitySet<opiniones_cliente> _opiniones_clientes;
		
		private EntitySet<reserva> _reservas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    #endregion
		
		public cliente()
		{
			this._opiniones_clientes = new EntitySet<opiniones_cliente>(new Action<opiniones_cliente>(this.attach_opiniones_clientes), new Action<opiniones_cliente>(this.detach_opiniones_clientes));
			this._reservas = new EntitySet<reserva>(new Action<reserva>(this.attach_reservas), new Action<reserva>(this.detach_reservas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(15)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_opiniones_cliente", Storage="_opiniones_clientes", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<opiniones_cliente> opiniones_clientes
		{
			get
			{
				return this._opiniones_clientes;
			}
			set
			{
				this._opiniones_clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_reserva", Storage="_reservas", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<reserva> reservas
		{
			get
			{
				return this._reservas;
			}
			set
			{
				this._reservas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_opiniones_clientes(opiniones_cliente entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_opiniones_clientes(opiniones_cliente entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
		
		private void attach_reservas(reserva entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_reservas(reserva entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.transporte")]
	public partial class transporte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_transporte;
		
		private string _tipo;
		
		private int _capacidad;
		
		private int _id_proveedor;
		
		private EntitySet<paquete> _paquetes;
		
		private EntityRef<proveedore> _proveedore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_transporteChanging(int value);
    partial void Onid_transporteChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OncapacidadChanging(int value);
    partial void OncapacidadChanged();
    partial void Onid_proveedorChanging(int value);
    partial void Onid_proveedorChanged();
    #endregion
		
		public transporte()
		{
			this._paquetes = new EntitySet<paquete>(new Action<paquete>(this.attach_paquetes), new Action<paquete>(this.detach_paquetes));
			this._proveedore = default(EntityRef<proveedore>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_transporte", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_transporte
		{
			get
			{
				return this._id_transporte;
			}
			set
			{
				if ((this._id_transporte != value))
				{
					this.Onid_transporteChanging(value);
					this.SendPropertyChanging();
					this._id_transporte = value;
					this.SendPropertyChanged("id_transporte");
					this.Onid_transporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacidad", DbType="Int NOT NULL")]
		public int capacidad
		{
			get
			{
				return this._capacidad;
			}
			set
			{
				if ((this._capacidad != value))
				{
					this.OncapacidadChanging(value);
					this.SendPropertyChanging();
					this._capacidad = value;
					this.SendPropertyChanged("capacidad");
					this.OncapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proveedor", DbType="Int NOT NULL")]
		public int id_proveedor
		{
			get
			{
				return this._id_proveedor;
			}
			set
			{
				if ((this._id_proveedor != value))
				{
					if (this._proveedore.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_proveedorChanging(value);
					this.SendPropertyChanging();
					this._id_proveedor = value;
					this.SendPropertyChanged("id_proveedor");
					this.Onid_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="transporte_paquete", Storage="_paquetes", ThisKey="id_transporte", OtherKey="id_transporte")]
		public EntitySet<paquete> paquetes
		{
			get
			{
				return this._paquetes;
			}
			set
			{
				this._paquetes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proveedore_transporte", Storage="_proveedore", ThisKey="id_proveedor", OtherKey="id_proveedor", IsForeignKey=true)]
		public proveedore proveedore
		{
			get
			{
				return this._proveedore.Entity;
			}
			set
			{
				proveedore previousValue = this._proveedore.Entity;
				if (((previousValue != value) 
							|| (this._proveedore.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._proveedore.Entity = null;
						previousValue.transportes.Remove(this);
					}
					this._proveedore.Entity = value;
					if ((value != null))
					{
						value.transportes.Add(this);
						this._id_proveedor = value.id_proveedor;
					}
					else
					{
						this._id_proveedor = default(int);
					}
					this.SendPropertyChanged("proveedore");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_paquetes(paquete entity)
		{
			this.SendPropertyChanging();
			entity.transporte = this;
		}
		
		private void detach_paquetes(paquete entity)
		{
			this.SendPropertyChanging();
			entity.transporte = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.excursiones")]
	public partial class excursiones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_excursion;
		
		private string _nombre;
		
		private string _descripcion;
		
		private decimal _precio;
		
		private int _capacidad;
		
		private EntitySet<paquetes_excursione> _paquetes_excursiones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_excursionChanging(int value);
    partial void Onid_excursionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    partial void OncapacidadChanging(int value);
    partial void OncapacidadChanged();
    #endregion
		
		public excursiones()
		{
			this._paquetes_excursiones = new EntitySet<paquetes_excursione>(new Action<paquetes_excursione>(this.attach_paquetes_excursiones), new Action<paquetes_excursione>(this.detach_paquetes_excursiones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_excursion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_excursion
		{
			get
			{
				return this._id_excursion;
			}
			set
			{
				if ((this._id_excursion != value))
				{
					this.Onid_excursionChanging(value);
					this.SendPropertyChanging();
					this._id_excursion = value;
					this.SendPropertyChanged("id_excursion");
					this.Onid_excursionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2) NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacidad", DbType="Int NOT NULL")]
		public int capacidad
		{
			get
			{
				return this._capacidad;
			}
			set
			{
				if ((this._capacidad != value))
				{
					this.OncapacidadChanging(value);
					this.SendPropertyChanging();
					this._capacidad = value;
					this.SendPropertyChanged("capacidad");
					this.OncapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="excursiones_paquetes_excursione", Storage="_paquetes_excursiones", ThisKey="id_excursion", OtherKey="id_excursion")]
		public EntitySet<paquetes_excursione> paquetes_excursiones
		{
			get
			{
				return this._paquetes_excursiones;
			}
			set
			{
				this._paquetes_excursiones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_paquetes_excursiones(paquetes_excursione entity)
		{
			this.SendPropertyChanging();
			entity.excursiones = this;
		}
		
		private void detach_paquetes_excursiones(paquetes_excursione entity)
		{
			this.SendPropertyChanging();
			entity.excursiones = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.facturas")]
	public partial class factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_factura;
		
		private int _id_reserva;
		
		private decimal _total;
		
		private System.Nullable<System.DateTime> _fecha_emision;
		
		private EntityRef<reserva> _reserva;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_facturaChanging(int value);
    partial void Onid_facturaChanged();
    partial void Onid_reservaChanging(int value);
    partial void Onid_reservaChanged();
    partial void OntotalChanging(decimal value);
    partial void OntotalChanged();
    partial void Onfecha_emisionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_emisionChanged();
    #endregion
		
		public factura()
		{
			this._reserva = default(EntityRef<reserva>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_factura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_factura
		{
			get
			{
				return this._id_factura;
			}
			set
			{
				if ((this._id_factura != value))
				{
					this.Onid_facturaChanging(value);
					this.SendPropertyChanging();
					this._id_factura = value;
					this.SendPropertyChanged("id_factura");
					this.Onid_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reserva", DbType="Int NOT NULL")]
		public int id_reserva
		{
			get
			{
				return this._id_reserva;
			}
			set
			{
				if ((this._id_reserva != value))
				{
					if (this._reserva.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_reservaChanging(value);
					this.SendPropertyChanging();
					this._id_reserva = value;
					this.SendPropertyChanged("id_reserva");
					this.Onid_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(10,2) NOT NULL")]
		public decimal total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_emision", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_emision
		{
			get
			{
				return this._fecha_emision;
			}
			set
			{
				if ((this._fecha_emision != value))
				{
					this.Onfecha_emisionChanging(value);
					this.SendPropertyChanging();
					this._fecha_emision = value;
					this.SendPropertyChanged("fecha_emision");
					this.Onfecha_emisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reserva_factura", Storage="_reserva", ThisKey="id_reserva", OtherKey="id_reserva", IsForeignKey=true)]
		public reserva reserva
		{
			get
			{
				return this._reserva.Entity;
			}
			set
			{
				reserva previousValue = this._reserva.Entity;
				if (((previousValue != value) 
							|| (this._reserva.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._reserva.Entity = null;
						previousValue.facturas.Remove(this);
					}
					this._reserva.Entity = value;
					if ((value != null))
					{
						value.facturas.Add(this);
						this._id_reserva = value.id_reserva;
					}
					else
					{
						this._id_reserva = default(int);
					}
					this.SendPropertyChanged("reserva");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.opiniones_clientes")]
	public partial class opiniones_cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_opinion;
		
		private int _id_cliente;
		
		private int _id_paquete;
		
		private string _comentario;
		
		private System.Nullable<int> _calificacion;
		
		private System.Nullable<System.DateTime> _fecha_publicacion;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<paquete> _paquete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_opinionChanging(int value);
    partial void Onid_opinionChanged();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Onid_paqueteChanging(int value);
    partial void Onid_paqueteChanged();
    partial void OncomentarioChanging(string value);
    partial void OncomentarioChanged();
    partial void OncalificacionChanging(System.Nullable<int> value);
    partial void OncalificacionChanged();
    partial void Onfecha_publicacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_publicacionChanged();
    #endregion
		
		public opiniones_cliente()
		{
			this._cliente = default(EntityRef<cliente>);
			this._paquete = default(EntityRef<paquete>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_opinion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_opinion
		{
			get
			{
				return this._id_opinion;
			}
			set
			{
				if ((this._id_opinion != value))
				{
					this.Onid_opinionChanging(value);
					this.SendPropertyChanging();
					this._id_opinion = value;
					this.SendPropertyChanged("id_opinion");
					this.Onid_opinionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int NOT NULL")]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paquete", DbType="Int NOT NULL")]
		public int id_paquete
		{
			get
			{
				return this._id_paquete;
			}
			set
			{
				if ((this._id_paquete != value))
				{
					if (this._paquete.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_paqueteChanging(value);
					this.SendPropertyChanging();
					this._id_paquete = value;
					this.SendPropertyChanged("id_paquete");
					this.Onid_paqueteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario", DbType="NVarChar(MAX)")]
		public string comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				if ((this._comentario != value))
				{
					this.OncomentarioChanging(value);
					this.SendPropertyChanging();
					this._comentario = value;
					this.SendPropertyChanged("comentario");
					this.OncomentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion", DbType="Int")]
		public System.Nullable<int> calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				if ((this._calificacion != value))
				{
					this.OncalificacionChanging(value);
					this.SendPropertyChanging();
					this._calificacion = value;
					this.SendPropertyChanged("calificacion");
					this.OncalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_publicacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_publicacion
		{
			get
			{
				return this._fecha_publicacion;
			}
			set
			{
				if ((this._fecha_publicacion != value))
				{
					this.Onfecha_publicacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_publicacion = value;
					this.SendPropertyChanged("fecha_publicacion");
					this.Onfecha_publicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_opiniones_cliente", Storage="_cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.opiniones_clientes.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.opiniones_clientes.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(int);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paquete_opiniones_cliente", Storage="_paquete", ThisKey="id_paquete", OtherKey="id_paquete", IsForeignKey=true)]
		public paquete paquete
		{
			get
			{
				return this._paquete.Entity;
			}
			set
			{
				paquete previousValue = this._paquete.Entity;
				if (((previousValue != value) 
							|| (this._paquete.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._paquete.Entity = null;
						previousValue.opiniones_clientes.Remove(this);
					}
					this._paquete.Entity = value;
					if ((value != null))
					{
						value.opiniones_clientes.Add(this);
						this._id_paquete = value.id_paquete;
					}
					else
					{
						this._id_paquete = default(int);
					}
					this.SendPropertyChanged("paquete");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.paquetes")]
	public partial class paquete : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_paquete;
		
		private string _nombre;
		
		private string _descripcion;
		
		private decimal _precio;
		
		private int _duracion_dias;
		
		private System.Nullable<int> _id_transporte;
		
		private EntitySet<opiniones_cliente> _opiniones_clientes;
		
		private EntitySet<reserva> _reservas;
		
		private EntitySet<paquetes_excursione> _paquetes_excursiones;
		
		private EntityRef<transporte> _transporte;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_paqueteChanging(int value);
    partial void Onid_paqueteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    partial void Onduracion_diasChanging(int value);
    partial void Onduracion_diasChanged();
    partial void Onid_transporteChanging(System.Nullable<int> value);
    partial void Onid_transporteChanged();
    #endregion
		
		public paquete()
		{
			this._opiniones_clientes = new EntitySet<opiniones_cliente>(new Action<opiniones_cliente>(this.attach_opiniones_clientes), new Action<opiniones_cliente>(this.detach_opiniones_clientes));
			this._reservas = new EntitySet<reserva>(new Action<reserva>(this.attach_reservas), new Action<reserva>(this.detach_reservas));
			this._paquetes_excursiones = new EntitySet<paquetes_excursione>(new Action<paquetes_excursione>(this.attach_paquetes_excursiones), new Action<paquetes_excursione>(this.detach_paquetes_excursiones));
			this._transporte = default(EntityRef<transporte>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paquete", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_paquete
		{
			get
			{
				return this._id_paquete;
			}
			set
			{
				if ((this._id_paquete != value))
				{
					this.Onid_paqueteChanging(value);
					this.SendPropertyChanging();
					this._id_paquete = value;
					this.SendPropertyChanged("id_paquete");
					this.Onid_paqueteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2) NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracion_dias", DbType="Int NOT NULL")]
		public int duracion_dias
		{
			get
			{
				return this._duracion_dias;
			}
			set
			{
				if ((this._duracion_dias != value))
				{
					this.Onduracion_diasChanging(value);
					this.SendPropertyChanging();
					this._duracion_dias = value;
					this.SendPropertyChanged("duracion_dias");
					this.Onduracion_diasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_transporte", DbType="Int")]
		public System.Nullable<int> id_transporte
		{
			get
			{
				return this._id_transporte;
			}
			set
			{
				if ((this._id_transporte != value))
				{
					if (this._transporte.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_transporteChanging(value);
					this.SendPropertyChanging();
					this._id_transporte = value;
					this.SendPropertyChanged("id_transporte");
					this.Onid_transporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paquete_opiniones_cliente", Storage="_opiniones_clientes", ThisKey="id_paquete", OtherKey="id_paquete")]
		public EntitySet<opiniones_cliente> opiniones_clientes
		{
			get
			{
				return this._opiniones_clientes;
			}
			set
			{
				this._opiniones_clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paquete_reserva", Storage="_reservas", ThisKey="id_paquete", OtherKey="id_paquete")]
		public EntitySet<reserva> reservas
		{
			get
			{
				return this._reservas;
			}
			set
			{
				this._reservas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paquete_paquetes_excursione", Storage="_paquetes_excursiones", ThisKey="id_paquete", OtherKey="id_paquete")]
		public EntitySet<paquetes_excursione> paquetes_excursiones
		{
			get
			{
				return this._paquetes_excursiones;
			}
			set
			{
				this._paquetes_excursiones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="transporte_paquete", Storage="_transporte", ThisKey="id_transporte", OtherKey="id_transporte", IsForeignKey=true)]
		public transporte transporte
		{
			get
			{
				return this._transporte.Entity;
			}
			set
			{
				transporte previousValue = this._transporte.Entity;
				if (((previousValue != value) 
							|| (this._transporte.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._transporte.Entity = null;
						previousValue.paquetes.Remove(this);
					}
					this._transporte.Entity = value;
					if ((value != null))
					{
						value.paquetes.Add(this);
						this._id_transporte = value.id_transporte;
					}
					else
					{
						this._id_transporte = default(Nullable<int>);
					}
					this.SendPropertyChanged("transporte");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_opiniones_clientes(opiniones_cliente entity)
		{
			this.SendPropertyChanging();
			entity.paquete = this;
		}
		
		private void detach_opiniones_clientes(opiniones_cliente entity)
		{
			this.SendPropertyChanging();
			entity.paquete = null;
		}
		
		private void attach_reservas(reserva entity)
		{
			this.SendPropertyChanging();
			entity.paquete = this;
		}
		
		private void detach_reservas(reserva entity)
		{
			this.SendPropertyChanging();
			entity.paquete = null;
		}
		
		private void attach_paquetes_excursiones(paquetes_excursione entity)
		{
			this.SendPropertyChanging();
			entity.paquete = this;
		}
		
		private void detach_paquetes_excursiones(paquetes_excursione entity)
		{
			this.SendPropertyChanging();
			entity.paquete = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.proveedores")]
	public partial class proveedore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_proveedor;
		
		private string _nombre;
		
		private string _contacto;
		
		private string _telefono;
		
		private EntitySet<transporte> _transportes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_proveedorChanging(int value);
    partial void Onid_proveedorChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncontactoChanging(string value);
    partial void OncontactoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    #endregion
		
		public proveedore()
		{
			this._transportes = new EntitySet<transporte>(new Action<transporte>(this.attach_transportes), new Action<transporte>(this.detach_transportes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proveedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_proveedor
		{
			get
			{
				return this._id_proveedor;
			}
			set
			{
				if ((this._id_proveedor != value))
				{
					this.Onid_proveedorChanging(value);
					this.SendPropertyChanging();
					this._id_proveedor = value;
					this.SendPropertyChanged("id_proveedor");
					this.Onid_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contacto", DbType="NVarChar(100)")]
		public string contacto
		{
			get
			{
				return this._contacto;
			}
			set
			{
				if ((this._contacto != value))
				{
					this.OncontactoChanging(value);
					this.SendPropertyChanging();
					this._contacto = value;
					this.SendPropertyChanged("contacto");
					this.OncontactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(15)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proveedore_transporte", Storage="_transportes", ThisKey="id_proveedor", OtherKey="id_proveedor")]
		public EntitySet<transporte> transportes
		{
			get
			{
				return this._transportes;
			}
			set
			{
				this._transportes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_transportes(transporte entity)
		{
			this.SendPropertyChanging();
			entity.proveedore = this;
		}
		
		private void detach_transportes(transporte entity)
		{
			this.SendPropertyChanging();
			entity.proveedore = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reservas")]
	public partial class reserva : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_reserva;
		
		private int _id_cliente;
		
		private int _id_paquete;
		
		private System.Nullable<System.DateTime> _fecha_reserva;
		
		private string _estado;
		
		private EntitySet<factura> _facturas;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<paquete> _paquete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_reservaChanging(int value);
    partial void Onid_reservaChanged();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Onid_paqueteChanging(int value);
    partial void Onid_paqueteChanged();
    partial void Onfecha_reservaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_reservaChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public reserva()
		{
			this._facturas = new EntitySet<factura>(new Action<factura>(this.attach_facturas), new Action<factura>(this.detach_facturas));
			this._cliente = default(EntityRef<cliente>);
			this._paquete = default(EntityRef<paquete>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reserva", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_reserva
		{
			get
			{
				return this._id_reserva;
			}
			set
			{
				if ((this._id_reserva != value))
				{
					this.Onid_reservaChanging(value);
					this.SendPropertyChanging();
					this._id_reserva = value;
					this.SendPropertyChanged("id_reserva");
					this.Onid_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int NOT NULL")]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paquete", DbType="Int NOT NULL")]
		public int id_paquete
		{
			get
			{
				return this._id_paquete;
			}
			set
			{
				if ((this._id_paquete != value))
				{
					if (this._paquete.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_paqueteChanging(value);
					this.SendPropertyChanging();
					this._id_paquete = value;
					this.SendPropertyChanged("id_paquete");
					this.Onid_paqueteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reserva", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_reserva
		{
			get
			{
				return this._fecha_reserva;
			}
			set
			{
				if ((this._fecha_reserva != value))
				{
					this.Onfecha_reservaChanging(value);
					this.SendPropertyChanging();
					this._fecha_reserva = value;
					this.SendPropertyChanged("fecha_reserva");
					this.Onfecha_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(20)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reserva_factura", Storage="_facturas", ThisKey="id_reserva", OtherKey="id_reserva")]
		public EntitySet<factura> facturas
		{
			get
			{
				return this._facturas;
			}
			set
			{
				this._facturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_reserva", Storage="_cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.reservas.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.reservas.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(int);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paquete_reserva", Storage="_paquete", ThisKey="id_paquete", OtherKey="id_paquete", IsForeignKey=true)]
		public paquete paquete
		{
			get
			{
				return this._paquete.Entity;
			}
			set
			{
				paquete previousValue = this._paquete.Entity;
				if (((previousValue != value) 
							|| (this._paquete.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._paquete.Entity = null;
						previousValue.reservas.Remove(this);
					}
					this._paquete.Entity = value;
					if ((value != null))
					{
						value.reservas.Add(this);
						this._id_paquete = value.id_paquete;
					}
					else
					{
						this._id_paquete = default(int);
					}
					this.SendPropertyChanged("paquete");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_facturas(factura entity)
		{
			this.SendPropertyChanging();
			entity.reserva = this;
		}
		
		private void detach_facturas(factura entity)
		{
			this.SendPropertyChanging();
			entity.reserva = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.paquetes_excursiones")]
	public partial class paquetes_excursione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_paquete_excursion;
		
		private int _id_paquete;
		
		private int _id_excursion;
		
		private EntityRef<excursiones> _excursiones;
		
		private EntityRef<paquete> _paquete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_paquete_excursionChanging(int value);
    partial void Onid_paquete_excursionChanged();
    partial void Onid_paqueteChanging(int value);
    partial void Onid_paqueteChanged();
    partial void Onid_excursionChanging(int value);
    partial void Onid_excursionChanged();
    #endregion
		
		public paquetes_excursione()
		{
			this._excursiones = default(EntityRef<excursiones>);
			this._paquete = default(EntityRef<paquete>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paquete_excursion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_paquete_excursion
		{
			get
			{
				return this._id_paquete_excursion;
			}
			set
			{
				if ((this._id_paquete_excursion != value))
				{
					this.Onid_paquete_excursionChanging(value);
					this.SendPropertyChanging();
					this._id_paquete_excursion = value;
					this.SendPropertyChanged("id_paquete_excursion");
					this.Onid_paquete_excursionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paquete", DbType="Int NOT NULL")]
		public int id_paquete
		{
			get
			{
				return this._id_paquete;
			}
			set
			{
				if ((this._id_paquete != value))
				{
					if (this._paquete.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_paqueteChanging(value);
					this.SendPropertyChanging();
					this._id_paquete = value;
					this.SendPropertyChanged("id_paquete");
					this.Onid_paqueteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_excursion", DbType="Int NOT NULL")]
		public int id_excursion
		{
			get
			{
				return this._id_excursion;
			}
			set
			{
				if ((this._id_excursion != value))
				{
					if (this._excursiones.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_excursionChanging(value);
					this.SendPropertyChanging();
					this._id_excursion = value;
					this.SendPropertyChanged("id_excursion");
					this.Onid_excursionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="excursiones_paquetes_excursione", Storage="_excursiones", ThisKey="id_excursion", OtherKey="id_excursion", IsForeignKey=true)]
		public excursiones excursiones
		{
			get
			{
				return this._excursiones.Entity;
			}
			set
			{
				excursiones previousValue = this._excursiones.Entity;
				if (((previousValue != value) 
							|| (this._excursiones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._excursiones.Entity = null;
						previousValue.paquetes_excursiones.Remove(this);
					}
					this._excursiones.Entity = value;
					if ((value != null))
					{
						value.paquetes_excursiones.Add(this);
						this._id_excursion = value.id_excursion;
					}
					else
					{
						this._id_excursion = default(int);
					}
					this.SendPropertyChanged("excursiones");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paquete_paquetes_excursione", Storage="_paquete", ThisKey="id_paquete", OtherKey="id_paquete", IsForeignKey=true)]
		public paquete paquete
		{
			get
			{
				return this._paquete.Entity;
			}
			set
			{
				paquete previousValue = this._paquete.Entity;
				if (((previousValue != value) 
							|| (this._paquete.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._paquete.Entity = null;
						previousValue.paquetes_excursiones.Remove(this);
					}
					this._paquete.Entity = value;
					if ((value != null))
					{
						value.paquetes_excursiones.Add(this);
						this._id_paquete = value.id_paquete;
					}
					else
					{
						this._id_paquete = default(int);
					}
					this.SendPropertyChanged("paquete");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NombreUsuario;
		
		private string _Contrasena;
		
		private string _Rol;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnRolChanging(string value);
    partial void OnRolChanged();
    partial void OnFechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCreacionChanged();
    #endregion
		
		public Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="NVarChar(50)")]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
